### ISSUE TITLE
`[dead]` posts not indexed

### ISSUE THREAD

**Issue by PatMyron** [algolia/hn-search#240] opened 2023-10-11 23:14 UTC
`[flagged]` posts are still indexed, but `[dead]` posts are not
https://news.ycombinator.com/newsfaq.html
Examples:
https://news.ycombinator.com/item?id=29220729
https://news.ycombinator.com/item?id=37790899

A setting to include `[dead]` posts could be useful

**Comment by jeffrey-slentz-algolia** [comment] 2023-10-12 16:58
We avoided indexing `[dead]` posts for storage optimization, since there's not much information left except the author. What's the use case for searching for deleted posts or comments?

**Comment by PatMyron** [comment] 2023-10-12 18:18
> not much information left

As mentioned in https://news.ycombinator.com/newsfaq.html, there's a setting to show the rest of their information:

> Dead posts aren't displayed by default, but you can see them all by turning on `showdead` in your profile

**Comment by jeffrey-slentz-algolia** [comment] 2023-10-12 19:12
Ah, I missed the difference between `dead` and `deleted`. Can you share an example of a `[dead]` post?

**Comment by PatMyron** [comment] 2023-10-12 19:57
> Examples:
> https://news.ycombinator.com/item?id=29220729
> https://news.ycombinator.com/item?id=37790899

These examples I linked are `[dead]` and only show for users who enabled `showdead`

**Comment by jeffrey-slentz-algolia** [comment] 2023-10-13 21:11
Oh I see.
We use the API to retrieve these posts, so the issue is that that information is not visible to us to index.

https://hacker-news.firebaseio.com/v0/item/29220729.json?print=pretty
https://hacker-news.firebaseio.com/v0/item/37790899.json?print=pretty

Without a way to retrieve the original story text, we can't make it searchable, unless there'd be a great value in showing [dead] posts when searching for posts by a specific author.

For example, this search [by:lalajollyton](https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=by%3A%20lalajollyton&sort=byPopularity&type=story) would show two results instead of the one result (and the dead item would have no title/link, just `[dead]`). 
https://hacker-news.firebaseio.com/v0/item/37785072.json?print=pretty
https://hacker-news.firebaseio.com/v0/item/37790899.json?print=pretty

**Comment by jeffrey-slentz-algolia** [comment] 2023-10-26 15:16
I'm going to close this one as won't do due to API restrictions. Thanks Pat!

**Closed as completed by jeffrey-slentz-algolia** 2023-10-26 15:16 UTC
